INSERT INTO burgers (burger_name, devoured) VALUES ('The Green Avocado Yoda Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('The Jedi Knight Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('The Big Death Star Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('The Luke SkyBurger Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('The Hairy Chewbacca Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('The Small Ewoke Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('The Light Saber Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('The Kylo Ren Burger', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('The Burger Awakens', false);
INSERT INTO burgers (burger_name, devoured) VALUES ('Reys Burger', false);
